version: '3.1'

services:
  db:
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PLATZHALTER
    volumes:
      - ./infrastructure/mariadb:/docker-entrypoint-initdb.d
      - mariadbvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --transaction-isolation=READ-COMMITTED

volumes:
  mariadbvolume:
