package de.signWritingEditor.shared.model.domainValue;

public enum SignDialectRegion {
	BADEN_WUERTTEMBERG, BAVARIA, BERLIN, BRANDENBURG, BREMEN, HAMBURG, HESSE, LOWER_SAXONY, MECKLENBURG_VORPOMMERN, NORTH_RHINE_WESTPHALIA, RHINELAND_PALATINATE, SAARLAND, SAXONY, SAXONY_ANHALT, SCHLESWIG_HOLSTEIN, THURINGIA;

}
